# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=64)),
                ('customer_name', models.CharField(max_length=64)),
                ('is_female', models.BooleanField()),
                ('area_id', models.CharField(db_index=True, max_length=64)),
                ('birthday', models.DateField()),
                ('online_time', models.DateTimeField()),
                ('offline_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Site'),
        ),
    ]
