# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='person_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
