# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180529_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleTeens',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('person_id', models.CharField(max_length=64)),
                ('age', models.PositiveIntegerField()),
                ('customer_name', models.CharField(max_length=64)),
                ('level', models.IntegerField(choices=[(1, 'High'), (2, 'Suspect')])),
                ('online_time', models.DateTimeField()),
                ('offline_time', models.DateTimeField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Site')),
            ],
        ),
        migrations.CreateModel(
            name='RecordAggregation1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_female', models.BooleanField()),
                ('age_label', models.PositiveIntegerField(choices=[(0, '-18'), (1, '19-25'), (2, '26-35'), (3, '36-45'), (4, '46-60'), (5, '61-')])),
                ('birthplace', models.PositiveIntegerField()),
                ('weekday', models.PositiveIntegerField()),
                ('hour', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Site')),
            ],
        ),
    ]
