# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_possibleteens_recordaggregation1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordaggregation1',
            name='birthplace',
        ),
        migrations.RemoveField(
            model_name='recordaggregation1',
            name='is_female',
        ),
    ]
