# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180530_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibleteens',
            name='level',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Suspect')], db_index=True),
        ),
        migrations.AlterField(
            model_name='recordaggregation1',
            name='age_label',
            field=models.PositiveIntegerField(choices=[(0, '-18'), (1, '19-25'), (2, '26-35'), (3, '36-45'), (4, '46-60'), (5, '61-')], db_index=True),
        ),
        migrations.AlterField(
            model_name='recordaggregation1',
            name='hour',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='recordaggregation1',
            name='weekday',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
