# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_suspectrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspectrelation',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Site'),
            preserve_default=False,
        ),
    ]
