# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_suspectrelation2'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordAggregation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveIntegerField(db_index=True)),
                ('hour', models.PositiveIntegerField(db_index=True)),
                ('migration', models.BooleanField(db_index=True)),
                ('count', models.PositiveIntegerField()),
                ('total_length', models.FloatField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Site')),
            ],
        ),
        migrations.CreateModel(
            name='RecordAggregation3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(db_index=True)),
                ('length', models.PositiveIntegerField(choices=[(1, '-1'), (2, '1-2'), (3, '2-3'), (5, '3-5'), (8, '5-8'), (13, '8-')], db_index=True)),
                ('migration', models.BooleanField(db_index=True)),
                ('count', models.PositiveIntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Site')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recordaggregation3',
            unique_together=set([('site', 'age', 'length', 'migration')]),
        ),
        migrations.AlterUniqueTogether(
            name='recordaggregation2',
            unique_together=set([('site', 'weekday', 'hour', 'migration')]),
        ),
    ]
